#!/usr/bin/env bash
# Deploy the current vault WASM to Stellar testnet and emit staging addresses.
# This script deliberately refuses non-testnet values.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WASM_PATH="$REPO_ROOT/neurowealth-vault/target/wasm32-unknown-unknown/release/neurowealth_vault.wasm"
OUTPUT_FILE="${STAGING_CONTRACTS_FILE:-$REPO_ROOT/scripts/staging-contracts.env}"

SOROBAN_RPC_URL="${SOROBAN_RPC_URL:-https://soroban-testnet.stellar.org}"
SOROBAN_NETWORK_PASSPHRASE="${SOROBAN_NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"
STAGING_DEPLOYER_SECRET_KEY="${STAGING_DEPLOYER_SECRET_KEY:-${SOROBAN_SECRET_KEY:-}}"

case "$SOROBAN_RPC_URL" in
  *soroban-testnet.stellar.org*) ;;
  *) echo "Refusing staging deployment: RPC is not Stellar testnet: $SOROBAN_RPC_URL" >&2; exit 1 ;;
esac
if [[ "$SOROBAN_NETWORK_PASSPHRASE" != "Test SDF Network ; September 2015" ]]; then
  echo "Refusing staging deployment: network passphrase is not Stellar testnet" >&2
  exit 1
fi

if ! command -v stellar >/dev/null 2>&1; then
  echo "The stellar CLI is required" >&2
  exit 1
fi

if [[ ! -f "$WASM_PATH" ]]; then
  RUSTFLAGS="-C target-cpu=mvp" cargo build \
    --manifest-path "$REPO_ROOT/neurowealth-vault/Cargo.toml" \
    --target wasm32-unknown-unknown --release
fi

if [[ -n "$STAGING_DEPLOYER_SECRET_KEY" ]]; then
  stellar keys add staging-deployer --secret-key "$STAGING_DEPLOYER_SECRET_KEY" \
    --network testnet 2>/dev/null || true
else
  stellar keys generate staging-deployer --network testnet --fund
fi

DEPLOYER_ADDRESS="$(stellar keys address staging-deployer)"
DEPLOY_OUTPUT="$(stellar contract deploy --wasm "$WASM_PATH" --source staging-deployer --network testnet)"
VAULT_CONTRACT_ID="$(printf '%s\n' "$DEPLOY_OUTPUT" | tail -1 | tr -d '[:space:]')"

TOKEN_OUTPUT="$(stellar contract asset deploy --asset native --source staging-deployer --network testnet 2>&1 || true)"
USDC_TOKEN_ADDRESS="$(printf '%s\n' "$TOKEN_OUTPUT" | tail -1 | tr -d '[:space:]')"
if [[ -z "$USDC_TOKEN_ADDRESS" || "$USDC_TOKEN_ADDRESS" == *Error* ]]; then
  USDC_TOKEN_ADDRESS="$(stellar contract id asset --asset native --source staging-deployer --network testnet | tail -1 | tr -d '[:space:]')"
fi

stellar contract invoke \
  --id "$VAULT_CONTRACT_ID" \
  --source staging-deployer \
  --network testnet \
  -- initialize \
  --agent "$DEPLOYER_ADDRESS" \
  --usdc_token "$USDC_TOKEN_ADDRESS"

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/deploy-staging.sh. Do not commit.
export STAGING_VAULT_CONTRACT_ID="$VAULT_CONTRACT_ID"
export STAGING_USDC_TOKEN_ADDRESS="$USDC_TOKEN_ADDRESS"
export STAGING_AGENT_ADDRESS="$DEPLOYER_ADDRESS"
export NEXT_PUBLIC_VAULT_CONTRACT_ID="$VAULT_CONTRACT_ID"
export NEXT_PUBLIC_SOROBAN_RPC_URL="$SOROBAN_RPC_URL"
export NEXT_PUBLIC_SOROBAN_NETWORK_PASSPHRASE="$SOROBAN_NETWORK_PASSPHRASE"
EOF

echo "Staging vault: $VAULT_CONTRACT_ID"
echo "Staging token: $USDC_TOKEN_ADDRESS"
echo "Staging agent: $DEPLOYER_ADDRESS"
echo "Environment written to: $OUTPUT_FILE"