mod test_access_control;
mod test_adversarial_agent_simulation;
mod test_agent_timelock;
mod test_approval_ttl;
mod test_asset_breakdown;
mod test_asset_decrease;
mod test_asset_split;
mod test_auth;
// mod test_balance_deprecation;
mod test_balance_shares_invariant;
#[cfg(feature = "blend-devnet")]
mod test_blend_devnet;
mod test_blend_integration;
mod test_budget;
mod test_checked_arithmetic;
mod test_circuit_breaker;
// Pre-existing compile failures (stale APIs / missing traits); not harvest coverage.
// mod test_concurrent_timelocks;
mod test_deposit;
#[cfg(feature = "dex-devnet")]
mod test_dex_devnet;
mod test_dex_integration;
mod test_emergency_harvest;
mod test_event_payloads;
mod test_event_schema;
mod test_events;
mod test_exchange_rate;
mod test_fuzz_deposit_withdraw;
mod test_get_user_strategy_unset;
mod test_harvest;
mod test_inflation_attack;
mod test_initialize;
mod test_legacy_inline;
mod test_limits;
mod test_math_limits;
mod test_multi_protocol;
mod test_multi_user_concurrent;
mod test_multi_asset;
mod test_no_privilege_escalation_proptest;
mod test_pause;
mod test_pool_config_idempotent;
mod test_pool_rotation_with_deployed_funds;
mod test_rate_limiting;
mod test_rebalance;
// mod test_rebalance_cooldown;
mod test_rebalance_integration;
// Pre-existing compile failures (MockTokenDataKey not #[contracttype], no std).
// mod test_reentrancy_defense;
mod test_require_initialized;
mod test_rounding_math;
mod test_rounding_small_amounts;
mod test_security_agent_drain;
mod test_share_conversion_proptest;
mod test_shares;
mod test_stale_state_audit;
mod test_storage_griefing_analysis;
mod test_strategy_switch_low_liquidity;
mod test_total_assets_cap;
mod test_transfer_delta_sanity;
mod test_ttl;
mod test_tvl_cap_serial;
mod test_tvl_cap_stress;
mod test_update_total_assets_blend;
mod test_update_total_assets_dex;
mod test_upgrade_compatibility;
// mod test_upgrade_timelock;
mod test_user_strategy;
mod test_users_with_shares;
mod test_withdraw;
// mod test_yield;
mod utils;

// WIP modules with known pre-existing compile issues:
// mod test_batch_deposit;
// mod test_insurance_fund;
// mod test_liquidity_mining_rewards;
// mod test_performance_fee;
// mod test_user_apy;
// mod test_withdrawal_queue;
// mod test_batch_touch_ttl;
// mod test_guardian;
mod test_lifecycle;
